Step1
next-step/spring-cart pull request #11
Opened 2023-04-12 13:21 UTC by aaaicu

2023-04-13 05:17 UTC, heowc requested changes
안녕하세요. 리뷰어를 맡게된 허원철입니다.

어느새 마지막 미션이네요~
마지막 미션인 만큼 더욱더 얻어가시는게 많으셨으면 좋겠습니다.

그런 의미에서 바로 머지하기엔 아쉬움이 있어 소소한 코멘트를 남겨보았어요.
확인해보시고 궁금하신 점이나 어려우신 점이 있다면 코멘트 or DM 부탁드립니다~ ✉️

2023-04-13 05:17 UTC, heowc commented on build.gradle
> +    compileOnly 'org.projectlombok:lombok'
jpa와 lombok을 추가하신 특별한 이유가 있을까요? 해당 미션에서는 기존 라이브러리/프레임워크만으로도 충분히 구현이 가능해서 여쭤봅니다 🤔

2023-04-13 05:17 UTC, heowc commented on src/main/java/cart/controller/CartApiController.java
> +public class CartApiController {
```suggestion
public class ProductApiController {
```
가 아닌 `CartApiController` 인 이유가 있을까요? 🤔 

1단계에서 구현되어야할 내용은 `상품 관리 CRUD API 작성`이라서요

2023-04-13 05:17 UTC, heowc commented on src/main/java/cart/service/ProductService.java
> +//                new Product(5, "상품5", "http://test.test", 2500));
사용하지 않는 코드는 제거해주시면 좋을 것 같습니다 👍

2023-04-13 05:17 UTC, heowc commented on src/main/resources/application.properties
> +spring.jpa.properties.hibernate.show_sql=true
해당 속성과 `spring.jpa.show-sql`은 서비스 코드에서 사용하는 것을 권장하지 않는데요. 왜 그럴까요 🤔 

https://www.baeldung.com/sql-logging-spring-boot

2023-04-13 05:17 UTC, heowc commented on src/main/resources/data.sql
> +CREATE TABLE PRODUCT (
`spring.jpa.hibernate.ddl-auto=create-drop` 설정해주셨다면 이 코드는 필요없지 않을까요? 🤔

2023-04-13 05:17 UTC, heowc commented on src/main/resources/static/js/admin.js
> +        headers: { 'Content-Type': 'application/json' },
👍

2023-04-13 05:17 UTC, heowc commented on README.md
> + - [X] 상품 관리 CRUD API 작성
관련해서 테스트 코드도 작성해주시면 더 좋을 것 같습니다 💪

2023-04-13 05:43 UTC, aaaicu commented on src/main/java/cart/service/ProductService.java
> +//                new Product(5, "상품5", "http://test.test", 2500));
늦은시간에 하다보니 테스트하기위한 값이 들어갔었네요 😅

2023-04-13 06:05 UTC, aaaicu commented on src/main/java/cart/controller/CartApiController.java
> +public class CartApiController {
CartApiController 가 적절하겠군요 
그렇게 변경할게요👍

2023-04-13 06:15 UTC, aaaicu commented on build.gradle
> +    compileOnly 'org.projectlombok:lombok'
미션 제약사항에 특별한 제약이없어서 간단하게 구현할 방법을 찾았었어요
JDBC 와 기본 프레임워크로 변경하여 push할게요!

2023-04-13 06:16 UTC, aaaicu commented on src/main/resources/data.sql
> +CREATE TABLE PRODUCT (
그렇게 보이네요.
위에서 먼저 말씀해주신대로 JPA를 빼고 sql파일은 유지하는 걸로 할게요

2023-04-13 08:57 UTC, aaaicu commented on src/main/resources/application.properties
> +spring.jpa.properties.hibernate.show_sql=true
로깅프레임워크의 최적화와 무관하게 동작해서 권장하지 않는군요!
참고할 수 있는 링크 주셔서 감사해요!

JPA를 제거하면서 해당 내용도 삭제하긴했습니다.

2023-04-14 12:05 UTC, aaaicu commented on README.md
> + - [X] 상품 관리 CRUD API 작성
테스트코드 추가했습니다 !

2023-04-15 08:37 UTC, heowc approved these changes
피드백 반영 감사합니다 👍 

소소한 코멘트를 남겨놨는데 확인 부탁드려요~
다음 단계를 진행해주세요 👍

2023-04-15 08:37 UTC, heowc commented on src/main/java/cart/controller/ProductApiController.java
> +    public ResponseEntity<Void> addProduct(@RequestBody Product product) {
도메인 계층 클래스가 컨트롤러 계층에서 참조되는 것이 바람직할지 고민해보시면 좋을 것 같습니다 🤔

2023-04-15 08:37 UTC, heowc commented on src/main/java/cart/domain/Product.java
> +    public static class ProductMapper implements RowMapper<Product> {
`RowMapper` 는 `spring-jdbc`에 특화된 클래스이기 때문에 여기보다는 `Repository`에 위치하는 것이 더 좋지 않을까요? 🤔

2023-04-15 08:37 UTC, heowc commented on src/test/java/cart/controller/ProductApiControllerTest.java
> +    private ProductService productService;
mock을 사용하신 이유가 있을까요? 🤔

2023-04-15 08:37 UTC, heowc commented on src/test/java/cart/repository/ProductRepositoryTest.java
> +    }
아래 테스트에서 `RestAssured`  사용하고 계시지 않는 것 같습니다 🤔

2023-04-15 08:37 UTC, merged

2023-04-15 10:44 UTC, aaaicu commented on src/main/java/cart/controller/ProductApiController.java
> +    public ResponseEntity<Void> addProduct(@RequestBody Product product) {
별도의 DTO성 클래스를 생성해서 매핑하도록 했습니다!
(ProductResponse, MemberResponse)

2023-04-15 10:45 UTC, aaaicu commented on src/test/java/cart/controller/ProductApiControllerTest.java
> +    private ProductService productService;
Service가 정상 동작한다고 가정할 때 Controller의 응답이 정상적으로 동작하는지 확인하고자 했습니다.
다른 방법을 고민해보는게 좋을까요? 🧐

2023-04-15 10:45 UTC, aaaicu commented on src/test/java/cart/repository/ProductRepositoryTest.java
> +    }
해당부분은 삭제했습니다!

2023-04-15 10:56 UTC, heowc commented on src/test/java/cart/controller/ProductApiControllerTest.java
> +    private ProductService productService;
개인적인 생각은 위 테스트로 인해 테스트하고자 하는 것이 무엇인지 불분명한 것 같아서요~

- `/product` API는 `ProductIntegrationTest`로 인해 테스트된 것으로 보이고
- 그걸 제외하고서라도 `ProductApiControllerTest`에서 테스트하고자 함이 무엇인지 보이지 않는 것 같습니다.
  - 가령, 응답에 대한 검증 처리
  - 결과 확인 등등
- 을 할 수 있을 것 같은데 그러진 않은 것 같아서요~ 🤔

2023-04-15 14:06 UTC, aaaicu commented on src/test/java/cart/controller/ProductApiControllerTest.java
> +    private ProductService productService;
아하! ProductIntegrationTest 에서 이미 모두 포함하고 있기때문에 중복코드로 보이네요
이 부분은 삭제하는게 좋겠네요!