ste
next-step/spring-cart pull request #5
Opened 2023-04-02 14:04 UTC by JinHyunYoung

2023-04-03 03:55 UTC, shared-moon requested changes
현영님 안녕하세요!
2단계 미션도 잘 진행 해 주셨네요 :)
마지막 미션이니 만큼 한번만 더 보고 가면 좋을 것 같아요!
코멘트를 좀 남겨 두었는데, 확인 후 리뷰 재요청 부탁드립니다 🔥

2023-04-03 03:55 UTC, shared-moon commented on src/main/java/cart/Service/CartService.java
> +    public int addCart(Cart cart) {
CartService이고 파라미터로 Cart를 받는데 메서드에 따로 명시 할 필요가 있을까요 ?

2023-04-03 03:55 UTC, shared-moon commented on src/main/java/cart/Service/CartService.java
> +        carts.stream().map(res -> {
`res` 는 약간 의미를 알아보기 힘들 것 같아요 :)

2023-04-03 03:55 UTC, shared-moon commented on src/main/java/cart/Service/CartService.java
> +            Product product = productDAO.selectProducts(res);
이렇게 되면 장바구니에 담긴 품목 수 만큼의 select쿼리가 추가로 나가게 되지 않을까요 ?

2023-04-03 03:55 UTC, shared-moon commented on src/main/java/cart/config/AuthInterceptor.java
> +            throw  new Exception("인증에 실패하였습니다.");
Exception 대신 더 명확한 예외를 사용할 수 없을까요 ?

2023-04-03 03:55 UTC, shared-moon commented on src/main/java/cart/controller/CartController.java
> +@RequestMapping("/cart")
개인적으로 저는 full path가 잘 드러나지 않아서 클래스에 path 지정은 잘 안하는 편이에요 :)

2023-04-03 03:55 UTC, shared-moon commented on src/main/java/cart/config/BasicAuthorizationExtractor.java
> +        String header = request.getHeader(AUTHORIZATION);
AUTHORIZATION은 여기서만 사용되는 것 같은데, 여기에 선언되어도 좋지 않을까요 ?

2023-04-03 03:55 UTC, shared-moon commented on src/main/java/cart/controller/CartController.java
> +        String email = (String) request.getAttribute("email");
`@RequestAttribute`를 사용해 보는 건 어떨까요 ?

2023-04-03 03:55 UTC, shared-moon commented on src/main/java/cart/dao/CartDAO.java
> +    public List<Cart> selectCarts(Cart cart) {
요런건 email만 받아도 되지 않을까요 ? JPA 사용시에는 이런 경우 findAllByEmail 정도로 메서드명이 만들어집니다!

2023-04-03 03:55 UTC, shared-moon commented on src/main/java/cart/dao/MemberDAO.java
> +    public boolean countMember(Member member) {
boolean 리턴이면 count~~ 라는 이름은 의미 전달이 조금 어렵지 않을까요 ?

2023-04-05 15:17 UTC, JinHyunYoung commented on src/main/java/cart/Service/CartService.java
> +    public int addCart(Cart cart) {
수정하였습니다.

2023-04-05 15:18 UTC, JinHyunYoung commented on src/main/java/cart/Service/CartService.java
> +            Product product = productDAO.selectProducts(res);
하나로 뽑아내도록 쿼리를 수정했습니다.

2023-04-05 15:18 UTC, JinHyunYoung commented on src/main/java/cart/config/BasicAuthorizationExtractor.java
> +        String header = request.getHeader(AUTHORIZATION);
수정하였습니다.

2023-04-05 15:19 UTC, JinHyunYoung commented on src/main/java/cart/controller/CartController.java
> +        String email = (String) request.getAttribute("email");
@RequestAttribute 대신  Resolver를 추가해서 세션에 받아서 추가했습니다.

2023-04-06 13:48 UTC, shared-moon approved these changes
현영님 안녕하세요!
피드백 반영 잘 진행 해 주셨네요 :)
이번 미션은 여기서 머지 하도록 하겠습니다.
정말 고생 많으셨어요!

2023-04-06 13:48 UTC, shared-moon commented on src/main/java/cart/Service/CartService.java
> +    public int add(Cart cart) {
👍

2023-04-06 13:48 UTC, shared-moon commented on src/main/java/cart/Service/ProductService.java
> +    public int add(Product product) {
👍

2023-04-06 13:48 UTC, shared-moon commented on src/main/java/cart/config/AuthInterceptor.java
> +            throw  new AuthorizationException("인증에 실패하였습니다.");
👍

2023-04-06 13:48 UTC, shared-moon commented on src/main/java/cart/dao/CartDAO.java
> +        String sql = "SELECT c.cart_id ,c.product_id ,  p.product_name , p.product_price , p.product_imagename  FROM CART c ,PRODUCT p where c.product_id = p.product_id and  user_email = ?";
👍

2023-04-06 13:48 UTC, merged