스프링카트 Step1
next-step/spring-cart pull request #7
Opened 2023-04-08 17:11 UTC by jadecyan

스프링카트 Step1

2023-04-09 12:50 UTC, mskangg requested changes
안녕하세요!
이번 미션 리뷰를 맡은 강민수입니다. 🙇‍♂️
스프링카트 기능 잘 구현해주셨네요! 👍 

그런데 테스트코드가 커밋에 빠진것 같습니당.
만약 빠진게 아니라면 테스트코드는 작성해야할 것 같아요!
그리고 소소한 피드백 남겨드렸으니 확인 부탁드립니다 🙏

2023-04-09 12:50 UTC, mskangg commented on README.md
> +[x]관리자 페이지에 상품 추가,삭제,수정 가능
👍

2023-04-09 12:50 UTC, mskangg commented on src/main/java/cart/controller/ProductController.java
> +    private MemberService memberService;
사용하지 않는 코드는 지우는게 좋을 것 같습니당 :)

2023-04-09 12:50 UTC, mskangg commented on src/main/java/cart/controller/ProductController.java
> +    }
모두 행위를 path에 정의해두셨네요!
post, delete, put, patch에 대해 알고계실까용??
rest하게 행위로 구분지어서 api를 작성해보시는것 추천드립니다! 👍

2023-04-09 12:50 UTC, mskangg commented on src/main/java/cart/controller/ProductController.java
> +        return new ResponseEntity(HttpStatus.OK);
새로운 리소스가 생겼으니 상태코드는 201로 넘기는건 어떨까요??

https://developer.mozilla.org/ko/docs/Web/HTTP/Status/201

2023-04-09 12:50 UTC, mskangg commented on src/main/java/cart/controller/ProductController.java
> +    @PostMapping("/createProduct")
Rest API에서 resource가 되는 값은 대부분 복수형으로 사용합니다.
여기에선 productes 혹은 products 가 되겠군요!

2023-04-09 12:50 UTC, mskangg commented on src/main/java/cart/controller/ProductController.java
> +    public ResponseEntity createProduct(@RequestBody Product product) {
현재 controller에서 api를 도메인 객체로 받고 있네요!
도메인 객체가 변경되면 api 스펙도 변경될 수도 있는 구조일 것 같아요! 🤔
관련된 링크 남겨드릴게요!

https://umbum.dev/1206

2023-04-09 12:50 UTC, mskangg commented on src/main/java/cart/service/ProductService.java
> +        productDao.insertProduct(product.getName(), product.getImageUrl(), product.getPrice());
dao 에 값을 꺼내서 넣는 것보다 도메인 객체를 생성하여 넘기는 것이 좋아보입니다!
그러면 자연스럽게 객체를 생성하면서 도메인의 유효성검증도 될것 같아요! 🤔

2023-04-12 11:37 UTC, mskangg requested changes
피드백 반영 잘해주셨어요!!
다만, 반영이 안된부분이 있어보여용
재요청 부탁드립니다 🙇

2023-04-12 11:37 UTC, mskangg commented on src/main/java/cart/controller/ProductController.java
> +    }
https://github.com/next-step/spring-cart/pull/7#discussion_r1161279021
피드백이 누락된 것 같아요..!

관련 링크 남겨드리겠습니다.

https://docs.oracle.com/en/cloud/saas/enterprise-performance-management-common/prest/rest_api_methods.html

https://velog.io/@ellyheetov/REST-API

2023-04-13 10:13 UTC, jadecyan commented on src/main/java/cart/controller/ProductController.java
> +    }
피드백 주신 부분 수정했습니다

2023-04-14 09:28 UTC, mskangg approved these changes
피드백 반영하시느라 고생많으셨습니다!!
그럼 이번 미션은 머지하도록 할게요! 🙇

2023-04-14 09:28 UTC, merged